sudo: false
language: php
matrix:
  fast_finish: true
  include:
  - php: '5.3'
  - php: '5.4'
  - php: '5.5'
  - php: '5.6'
  - php: '7.0'
  - php: '7.1'
before_script:
- export PHPCS_DIR=/tmp/phpcs
- export SNIFFS_DIR=/tmp/sniffs
- git clone -b 2.9 --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
- git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
  $SNIFFS_DIR
- git clone -b master --depth 1 https://github.com/wimg/PHPCompatibility.git $SNIFFS_DIR/PHPCompatibility
- "$PHPCS_DIR/scripts/phpcs --config-set installed_paths $SNIFFS_DIR"
- phpenv rehash
- npm install -g jscs
- npm install -g jshint
- wget https://develop.svn.wordpress.org/trunk/.jshintrc
- npm install -g grunt-cli
- npm install
- npm install -g grunt-checktextdomain
script:
- mkdir -p build/logs
- find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
- jshint ./assets/js/*.js
- jscs ./assets/js/*.js
- grunt textdomain
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./*.php --standard=./phpcs.ruleset.xml --extensions=php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php"
- "$PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php"
notifications:
  email: false
cache:
  directories:
  - node_modules
after_success:
- grunt build-archive
- sh set_tags.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: EMQ9rD9t7ErWFGZRaV5yrbvMDTFbb2UEFvEGxm395yIayyu3Zf7TXmGZvwOP3PDqrxGrsU92k+5cuv09R1uqejVFz+CcUcZzPjxQacU3L7UKoC34uTu20bVU3z1sSXaJilwySDGp3UQ39SdN3fm6/OYJBwWtsYEeAqPHhKPECxpke8UsEAdMguBHjSmn373QBhCgI2Hpq8OmyRsZKWYcGvBgQiEbqu7OE4AU3KEkZZZroIZzQLYNBApb3qnZhTAg80epJEw8wEejfZLBu7TvbWNnj3xD2km4DQ3hKHQRj6VYJ473Zlc6c1/ybEDBF7hyP+Iv0Ve3EePS/OoOrmPpoxkgNDnXWdJDj9Tz2Y1zI0hcxzggMIv5FsVaOUNAMpV+6d7d+k0Joe6S6MUX+jWPk6LNpyiEwK/D4FXx3KV9irtyAj6bkq+vowXiChZDN0Q72W4n8IugHHytUtpOY8sQyd5+ngKvnWHIG/sx/nPTXNlDrPUUjWGGwZPGcQ+FOje4ogzsn9gXBB7gzhmOxGDLNxOedIr9IBu5zE/U4WzjC5lv2yYiT/nAWS2e8/T+RWwwR+e8Kgsq4SA6C3R4mDD1lyC29B4EtenolKbEveeSBbyefsJfQ72nWGad3+s6QPeSQdwYVI5FsVu482XsSRiDxKU5yLx38IvPN5SQeXGW6cs=
  file: shapely-companion.zip
  on:
    branch: master
    repo: puikinsh/shapely-companion